$(document).ready ->

  createEvent = (title, start, end, allDay) ->
    #event登録
    event = 
      title: title
      start: start
      end: end
      allDay: allDay
    data = event: event
    $.ajax
      type: 'POST'
      url: '/calendar'
      data: 'user_events_path'
      dataType: 'json'
      success: ->
        $('#calendar').fullCalendar 'refetchEvents'
        #refetchEventsを呼んでデータの再取得・再描画を行う
        return
    return

  updateEvent = (event, revertFunc) ->
    #event更新
    url = '/events/' + event.id
    data = 
      _method: 'PUT'
      event:
        title: event.title
        start: event.start
        end: event.end
        allDay: event.allDay
    $.ajax
      type: 'POST'
      url: '/calendar'
      data: 'user_id: current_user.id'
      success: ->
        $('#calendar').fullCalendar 'refetchEvents'
        return
      error: revertFunc
    return

  deleteEvent = (event) ->
    #event削除
    url = '/events' + event.id
    data = _method: 'DELETE'
    $.ajax
      type: 'POST'
      url: '/calendar'
      data: 'user_id: current_user.id'
      success: ->
        $('#calendar').fullCalendar 'updateEvent', event
        return
    return

  select = (start, end, allDay) ->
    createDialog.find('#title').val ''
    createDialog.dialog 'option', 'buttons', [
      {
        text: 'OK'
        click: ->
          title = createDialog.find('#title').val()
          if title
            createEvent title, start, end, allDay
          createDialog.dialog 'close'
          $('#calendar').fullCalendar 'unselect'
          return

      }
      {
        text: 'Cancel'
        click: ->
          updateDialog.dialog 'close'
          $('#calendar').fullCalendar 'unselect'
          return

      }
    ]
    createDialog.dialog 'open'
    return

  eventClick = (event) ->
    updateDialog.find('#title').val event.title
    updateDialog.dialog 'option', 'buttons', [
      {
        text: 'OK'
        click: ->
          event.title = updateDialog.find('#title').val()
          updateEvent event, ->
          updateDialog.dialog 'close'
          $('#calendar').fullCalendar 'unselect'
          return

      }
      {
        text: 'Delete'
        click: ->
          deleteEvent event
          updateDialog.dialog 'close'
          $('#calendar').fullCalendar 'unselect'
          return

      }
      {
        text: 'Cancel'
        click: ->
          updateDialog.dialog 'close'
          $('#calendar').fullCalendar 'unselect'
          return

      }
    ]
    updateDialog.dialog 'open'
    return

  eventResize = (event, dayDelta, minuteDelta, revertFunc) ->
    updateEvent event, revertFunc
    return

  eventDrop = (event, dayDelta, minuteDelta, revertFunc) ->
    updateEvent event, revertFunc
    return

  createDialog = $('#eventdialog').dialog(
    autoOpen: false
    modal: true
    title: 'Create Event')
  updateDialog = $('#eventdialog').dialog(
    autoOpen: false
    modal: true
    title: 'Edit Event')
  return

# ---
# generated by js2coffee 2.1.0
# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
